/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.TaskController;
import java.util.Date;
import model.Task;


public class Main {

    public static void main(String[] args) {
       
      TaskController taskController = new TaskController();
      
      Task task = new Task();
      task.setIdProject(1);
      task.setName("Criar task nesse projeto");
      task.setNotes("Sem notas");
      task.setIsCompleted(false);
      task.setDeadline(new Date());
      
      taskController.save(task);
      
      
    }

}
